
#################################
#
#  NOTE: Do not edit this file.
#

import sys
from nqueens import solve
import time

if len(sys.argv) != 2:
    print("\n\tUsage: python3 run.py <test-file>\n")
    exit(1)

in_file = sys.argv[1]

problems = []

with open(in_file) as f:
    problems = map(int, f.readlines())


def print_answer(solve):
    for row in range(len(solve)):
        for col in range(len(solve)):
            print('Q' if solve[col] == row + 1 else '_', end=" ")
        print("")


for p in problems:
    t1 = time.time()
    answer = solve(p)
    t2 = time.time()

    # print(answer)
    print("Time elapsed for n=", p, "is", t2-t1)
    # print_answer(answer)
    print("\n")
